apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed-service
  labels:
    app: udagram-api-feed-service
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: udagram-api-feed-service